# Generated by Django 3.2.6 on 2021-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('Sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Cpf', models.IntegerField(verbose_name='Cpf')),
                ('Identidade', models.IntegerField(verbose_name='Identidade')),
                ('Idade', models.IntegerField(verbose_name='Idade')),
            ],
        ),
    ]
