# Generated by Django 3.2.6 on 2021-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cpf',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Identidade',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Identidade'),
        ),
    ]
